### ISSUE TITLE
Missing repo

### ISSUE THREAD

**Issue by robmarkcole** [IGNF/FLAIR#2]
https://ignf.github.io/FLAIR/ points to https://github.com/IGNF/FLAIR-1-AI-Challenge which does not exist

**Comment by agarioud** [comment]
Dear @robmarkcole , 
The Flair#1 repository to which the link points will be made public very soon. 
Sorry for the inconvenience.

**Comment by robmarkcole** [comment]
Thanks @agarioud I suspected that was the case. If you can close this issue when public that will alert me, and I will share some info on social media etc
Cheers

**Comment by agarioud** [comment]
Will do! 
Thanks @robmarkcole and don't hesitate to contact us if you need further informations.

**Comment by agarioud** [comment]
Closing the issue, as the FLAIR#1 repository is now public.
